//  The built-in glyphs the collection icon picker offers. The full set is generated by
//  `scripts/generate-symbol-catalog.py`; a small inline set stands in when the resource is absent.

import Foundation

/// One catalog glyph: its SF Symbol name, its browse category and the extra search terms the picker
/// matches against.
public struct OPNCollectionSymbol: Hashable, Sendable {
    public let name: String
    public let category: String
    let keywords: [String]
}

/// One picker category.
public struct OPNCollectionSymbolCategory: Hashable, Sendable, Identifiable {
    public let id: String
    public let title: String
}

/// The symbol universe and the two queries the picker runs: by category, and by search text.
public enum OPNCollectionSymbolCatalog {
    public static let allCategoryID = "__opn_all_symbols__"
    /// The picker's opening chip: a hand-picked spread of recognizable glyphs, because "All" starts
    /// at the numeric and letter symbols and reads as noise before a search or a category is chosen.
    public static let popularCategoryID = "__opn_popular_symbols__"

    public static var symbols: [OPNCollectionSymbol] { catalog.symbols }
    public static var categories: [OPNCollectionSymbolCategory] { catalog.categories }

    private static let catalog = loadCatalog()
    private static let symbolsByCategory: [String: [OPNCollectionSymbol]] = Dictionary(grouping: catalog.symbols, by: \.category)
    private static let symbolsByName: [String: OPNCollectionSymbol] = Dictionary(
        catalog.symbols.map { ($0.name, $0) },
        uniquingKeysWith: { first, _ in first }
    )

    /// The curated spread the "Popular" chip draws, looked up against whichever catalog loaded so a
    /// name this platform does not carry is simply absent.
    public static let popular: [OPNCollectionSymbol] = popularNames.compactMap { symbolsByName[$0] }

    public static func symbols(in categoryID: String) -> [OPNCollectionSymbol] {
        switch categoryID {
        case popularCategoryID: return popular
        case allCategoryID: return symbols
        default: return symbolsByCategory[categoryID] ?? symbols
        }
    }

    private static let popularNames = [
        "gamecontroller.fill", "arcade.stick", "trophy.fill", "crown.fill", "medal.fill",
        "star.fill", "heart.fill", "bolt.fill", "flame.fill", "sparkles", "wand.and.stars",
        "leaf.fill", "pawprint.fill", "dice.fill", "chess.piece.knight.fill", "puzzlepiece.fill",
        "person.2.fill", "figure.run", "figure.walk", "book.fill", "graduationcap.fill",
        "music.note", "headphones", "film.fill", "photo.fill", "camera.fill",
        "paintpalette.fill", "paintbrush.fill", "folder.fill", "shippingbox.fill", "cart.fill",
        "gift.fill", "tag.fill", "house.fill", "sofa.fill", "car.fill", "airplane",
        "bicycle", "sailboat.fill", "map.fill", "globe", "location.fill", "compass.drawing",
        "cloud.sun.fill", "moon.stars.fill", "snowflake", "sun.max.fill", "tornado",
        "desktopcomputer", "laptopcomputer", "iphone", "applewatch", "tv.fill",
        "antenna.radiowaves.left.and.right", "wifi", "envelope.fill", "message.fill", "phone.fill",
        "paperplane.fill", "lock.fill", "key.fill", "eye.fill", "keyboard.fill", "command",
        "clock.fill", "calendar", "alarm.fill", "hourglass", "fork.knife", "cup.and.saucer.fill",
        "birthday.cake.fill", "wineglass.fill", "pills.fill", "cross.case.fill", "stethoscope",
        "dumbbell.fill", "sportscourt.fill", "flag.fill", "a.circle.fill", "arrow.forward.circle.fill",
        "circle.grid.2x2.fill", "triangle.fill", "hexagon.fill", "seal.fill", "function",
        "textformat", "slider.horizontal.3", "crop", "gamecontroller", "star", "heart", "bolt",
        "shield.fill", "flashlight.on.fill", "guitars.fill", "pianokeys",
    ]

    /// Every symbol matching each search term, best first. An empty query returns the category
    /// unchanged, so the picker can iterate the whole set without a second call shape.
    public static func search(_ query: String, categoryID: String) -> [OPNCollectionSymbol] {
        let terms = query
            .lowercased()
            .split(whereSeparator: { !$0.isLetter && !$0.isNumber })
            .map(String.init)
        let pool = symbols(in: categoryID)
        guard !terms.isEmpty else { return pool }
        return pool
            .compactMap { symbol -> (symbol: OPNCollectionSymbol, score: Int)? in
                let score = matchScore(symbol, terms: terms)
                return score < 0 ? nil : (symbol, score)
            }
            .sorted { $0.score == $1.score ? $0.symbol.name < $1.symbol.name : $0.score > $1.score }
            .map(\.symbol)
    }

    // MARK: - Matching

    private static func matchScore(_ symbol: OPNCollectionSymbol, terms: [String]) -> Int {
        let name = symbol.name.lowercased()
        let tokens = name.split(separator: ".").map(String.init)
        var total = 0
        for term in terms {
            if tokens.contains(term) {
                total += 100
            } else if tokens.contains(where: { $0.hasPrefix(term) }) {
                total += 60
            } else if symbol.keywords.contains(term) {
                total += 50
            } else if symbol.keywords.contains(where: { $0.hasPrefix(term) }) {
                total += 25
            } else if name.contains(term) {
                total += 30
            } else if symbol.category.contains(term) {
                total += 10
            } else {
                return -1
            }
        }
        return total
    }

    // MARK: - Loading

    private struct Catalog {
        var symbols: [OPNCollectionSymbol]
        var categories: [OPNCollectionSymbolCategory]
    }

    private struct FileRecord: Decodable {
        let categories: [FileCategory]
        let symbols: [FileSymbol]
    }

    private struct FileCategory: Decodable {
        let key: String
        let title: String
    }

    private struct FileSymbol: Decodable {
        let name: String
        let category: String
        let keywords: [String]
    }

    private static func loadCatalog() -> Catalog {
        decodeBundledCatalog() ?? fallbackCatalog
    }

    private static func decodeBundledCatalog() -> Catalog? {
        for subdirectory in ["Resources/CollectionIcons", "CollectionIcons", nil] as [String?] {
            guard let url = Bundle.main.url(forResource: "sf-symbols", withExtension: "json", subdirectory: subdirectory),
                  let data = try? Data(contentsOf: url),
                  let record = try? JSONDecoder().decode(FileRecord.self, from: data) else { continue }
            let symbols = record.symbols.map { OPNCollectionSymbol(name: $0.name, category: $0.category, keywords: $0.keywords) }
            let categories = record.categories.map { OPNCollectionSymbolCategory(id: $0.key, title: $0.title) }
            guard !symbols.isEmpty, !categories.isEmpty else { continue }
            return Catalog(symbols: symbols, categories: categories)
        }
        return nil
    }

    private static func entry(_ name: String, _ category: String) -> OPNCollectionSymbol {
        OPNCollectionSymbol(name: name, category: category, keywords: [])
    }

    private static let fallbackCatalog: Catalog = {
        let pairs: [(String, String)] = [
            ("square.stack.3d.up.fill", "objectsandtools"), ("star.fill", "objectsandtools"),
            ("heart.fill", "health"), ("bolt.fill", "nature"), ("flame.fill", "nature"),
            ("leaf.fill", "nature"), ("pawprint.fill", "nature"), ("trophy.fill", "objectsandtools"),
            ("crown.fill", "objectsandtools"), ("shield.fill", "privacyandsecurity"),
            ("gamecontroller.fill", "gaming"), ("arcade.stick", "gaming"), ("dice.fill", "gaming"),
            ("chess.piece.knight.fill", "gaming"), ("puzzlepiece.fill", "objectsandtools"),
            ("person.2.fill", "human"), ("figure.run", "fitness"), ("person.crop.circle.fill", "human"),
            ("book.fill", "objectsandtools"), ("graduationcap.fill", "objectsandtools"),
            ("music.note", "media"), ("music.note.list", "media"), ("headphones", "media"),
            ("film.fill", "media"), ("photo.fill", "cameraandphotos"), ("camera.fill", "cameraandphotos"),
            ("paintpalette.fill", "draw"), ("paintbrush.fill", "draw"), ("scribble", "draw"),
            ("wand.and.stars", "draw"), ("sparkles", "nature"),
            ("folder.fill", "objectsandtools"), ("tray.fill", "objectsandtools"),
            ("archivebox.fill", "objectsandtools"), ("shippingbox.fill", "commerce"),
            ("cart.fill", "commerce"), ("gift.fill", "commerce"), ("tag.fill", "commerce"),
            ("bag.fill", "commerce"), ("creditcard.fill", "commerce"),
            ("house.fill", "home"), ("sofa.fill", "home"), ("bed.double.fill", "home"),
            ("lightbulb.fill", "home"), ("lamp.desk.fill", "home"),
            ("car.fill", "automotive"), ("airplane", "transportation"), ("bicycle", "transportation"),
            ("sailboat.fill", "transportation"), ("bus.fill", "transportation"), ("tram.fill", "transportation"),
            ("map.fill", "maps"), ("globe", "maps"), ("location.fill", "maps"), ("mappin.and.ellipse", "maps"),
            ("compass.drawing", "maps"),
            ("cloud.sun.fill", "weather"), ("moon.stars.fill", "weather"), ("snowflake", "weather"),
            ("sun.max.fill", "weather"), ("tornado", "weather"), ("umbrella.fill", "weather"),
            ("desktopcomputer", "devices"), ("laptopcomputer", "devices"), ("iphone", "devices"),
            ("applewatch", "devices"), ("headphones", "devices"), ("tv.fill", "devices"),
            ("printer.fill", "devices"), ("camera.metering.matrix", "devices"),
            ("antenna.radiowaves.left.and.right", "connectivity"), ("wifi", "connectivity"),
            ("bolt.horizontal.circle.fill", "connectivity"), ("network", "connectivity"),
            ("envelope.fill", "communication"), ("message.fill", "communication"),
            ("phone.fill", "communication"), ("bubble.left.and.bubble.right.fill", "communication"),
            ("paperplane.fill", "communication"),
            ("lock.fill", "privacyandsecurity"), ("key.fill", "privacyandsecurity"),
            ("eye.fill", "privacyandsecurity"), ("checkmark.shield.fill", "privacyandsecurity"),
            ("keyboard.fill", "keyboard"), ("command", "keyboard"), ("option", "keyboard"),
            ("clock.fill", "time"), ("calendar", "time"), ("timer", "time"), ("hourglass", "time"),
            ("alarm.fill", "time"),
            ("suitcase.fill", "objectsandtools"), ("backpack.fill", "objectsandtools"),
            ("cup.and.saucer.fill", "objectsandtools"), ("fork.knife", "objectsandtools"),
            ("birthday.cake.fill", "objectsandtools"), ("wineglass.fill", "objectsandtools"),
            ("pills.fill", "health"), ("cross.case.fill", "health"), ("stethoscope", "health"),
            ("dumbbell.fill", "fitness"), ("figure.walk", "fitness"), ("sportscourt.fill", "fitness"),
            ("flag.fill", "objectsandtools"), ("number", "indices"), ("a.circle.fill", "indices"),
            ("arrow.forward.circle.fill", "arrows"), ("arrow.up.right", "arrows"),
            ("circle.grid.2x2.fill", "shapes"), ("square.on.circle", "shapes"),
            ("triangle.fill", "shapes"), ("hexagon.fill", "shapes"), ("seal.fill", "shapes"),
            ("function", "math"), ("plus.forwardslash.minus", "math"), ("x.squareroot", "math"),
            ("accessibility", "accessibility"), ("eye.circle.fill", "accessibility"),
            ("ear.fill", "accessibility"), ("hand.raised.fill", "accessibility"),
            ("textformat", "textformatting"), ("bold", "textformatting"), ("character", "textformatting"),
            ("slider.horizontal.3", "editing"), ("wand.and.rays", "editing"), ("crop", "editing")
        ]
        let symbols = pairs.map { entry($0.0, $0.1) }
        let titles: [String: String] = [
            "objectsandtools": "Objects & Tools", "gaming": "Gaming", "media": "Media",
            "human": "Human", "fitness": "Fitness", "nature": "Nature", "health": "Health",
            "communication": "Communication", "weather": "Weather", "maps": "Maps",
            "devices": "Devices", "connectivity": "Connectivity", "transportation": "Transportation",
            "automotive": "Automotive", "home": "Home", "commerce": "Commerce", "draw": "Draw",
            "cameraandphotos": "Camera & Photos", "privacyandsecurity": "Privacy & Security",
            "accessibility": "Accessibility", "editing": "Editing", "textformatting": "Text Formatting",
            "keyboard": "Keyboard", "time": "Time", "shapes": "Shapes", "arrows": "Arrows",
            "indices": "Indices", "math": "Math"
        ]
        let order = titles.keys.sorted { (titles[$0] ?? $0) < (titles[$1] ?? $1) }
        let categories = order.map { OPNCollectionSymbolCategory(id: $0, title: titles[$0] ?? $0) }
        return Catalog(symbols: symbols, categories: categories)
    }()
}
